name: LDeAngelo
favicon: null
layout_spectrum: 0.4314775492530316
typography_spectrum: 0.6662774153519422
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05740267317742109
  lightness: 0.8944657174870372
  saturation: 0.03864034381695092
  rhythmicContrast: 0.8397100134752691
purpose: []
